version: "3.3"
services:
  spring-app:
    image: ru.ibikmetov.kotlin.realestateagency/ok-202202-real-estate-agency-spring:1.0
    container_name: real-estate-agency-restapi
    ports:
      - "8082:8082"
    depends_on:
      - cassandra
      - zookeeper
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./kfdata:/kafka
    links:
      - zookeeper
    environment:
      # Во внутренней сети docker-compose слушаем адрес kafka:9092
      # Из внешней сети docker-compose будем слушать localhost:9094
      # Как альтерантива, можно вычислять адрес как-то так:
      # HOSTNAME_COMMAND: curl http://169.254.169.254/latest/meta-data/public-hostname
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT

      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094,PLAINTEXT_INTERNAL://kafka:9092


      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix

  kafka-app:
    image: ok-202202-real-estate-agency-async:1.0
    container_name: real-estate-agency-async
    depends_on:
      - kafka